development:
  adapter: postgresql
  encoding: unicode
  database: stant_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: stant_rspec
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: your_production_db
  username: your_production_username
  password: your_production_pass