development:
  adapter: <%= ENV['ADAPTER'] %>
  encoding: unicode
  database: <%= ENV['POSTGRES_DATABASE'] %>
  host: database_postgresql
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: <%= ENV['ADAPTER'] %>
  encoding: unicode
  database: <%= ENV['POSTGRES_DATABASE_TEST'] %>
  host: database_postgresql
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %>
